//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDIWebSite.SQL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImgSection
    {
        public int IdImg { get; set; }
        public int IdCategory { get; set; }
        public byte[] Img { get; set; }
        public int Active { get; set; }
    
        public virtual CategorySection CategorySection { get; set; }
    }
}
